import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { AuthProvider } from "./AuthProvider";
import {RegisterLink, LoginLink, LogoutLink} from "@kinde-oss/kinde-auth-nextjs/components";
import {getKindeServerSession} from "@kinde-oss/kinde-auth-nextjs/server";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const {getUser} = getKindeServerSession();
    const user = await getUser();
  const {isAuthenticated} = getKindeServerSession();
  const isUserAuthenticated = await isAuthenticated();
  
  console.log(isUserAuthenticated);
  return (
    <AuthProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-green-600 px-4 py-8">
          <nav className="flex justify-between items-center gap-6 container mx-auto">
            <div>
              <Link className="text-lg font-bold" href='/'>TheBlogs</Link>
            </div>
            <div>
              <ul className="flex items-center justify-center gap-6">
                <li><Link href='/'>Home</Link></li>
                <li><Link href='/profile'>Profile</Link></li>
                <li><Link href='/login'>login</Link></li>
              </ul>
            </div>
            <div className="flex gap-6 ">
              {
                isUserAuthenticated ? <div className="flex items-center gap-2">
                <span className="font-bold">{user?.family_name}</span>
                <LogoutLink className="py-1 px-3 bg-green-400 rounded-md">Logout</LogoutLink>
                </div> : <>
                 <LoginLink className="py-1 px-3 bg-green-400 rounded-md">Sign in</LoginLink>
                 <RegisterLink className="py-1 px-3 bg-green-400 rounded-md">Register</RegisterLink>
                </>
              }
             
            </div>
          </nav>
        </div>

        <div className="container mx-auto px-4">
          {children}
        </div>

      </body>
    </html>
    </AuthProvider>
  );
}
